export default {
  data: [
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/favicon.ico' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/favicon.ico' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/favicon.ico' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff27b26c850>, 'path_info': '/favicon.ico', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/favicon.ico', 'path': '|/favicon.ico', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "13862482204440359931",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "http://127.0.0.1:9030/",
      requestargs: "{}",
      requestpath: "/favicon.ico",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T15:12:17.328440Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff27922f490>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "1184879541727452357",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:47:03.048074Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff279099850>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "713113453398824258",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:47:01.633168Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff27926c220>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "12878544007613931907",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:47:00.404740Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff279197280>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "15609571062307469600",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:46:57.801391Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff279094b80>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "3797465803257425685",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:46:55.753420Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/favicon.ico' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/favicon.ico' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/favicon.ico' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff27b26c7c0>, 'path_info': '/favicon.ico', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/favicon.ico', 'path': '|/favicon.ico', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "12130323417316868953",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "http://127.0.0.1:9030/logout",
      requestargs: "{}",
      requestpath: "/favicon.ico",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:46:53.793678Z",
    },
    {
      code: 404,
      errormsg:
        "b'404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.'",
      errortraceback:
        "File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1523, in full_dispatch_request<br>  rv = self.dispatch_request()<br>variables: {'self': <Flask 'elog'>, 'rv': None, 'e': <NotFound '404: Not Found'>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1499, in dispatch_request<br>  self.raise_routing_exception(req)<br>variables: {'self': <Flask 'elog'>, 'req': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/app.py\", line 1481, in raise_routing_exception<br>  raise request.routing_exception  # type: ignore<br>variables: {'self': <Flask 'elog'>, 'request': <Request 'http://127.0.0.1:9030/logout' [GET]>}<br><br>File \"/usr/local/lib/python3.8/site-packages/flask/ctx.py\", line 397, in match_request<br>  result = self.url_adapter.match(return_rule=True)  # type: ignore<br>variables: {'self': <RequestContext 'http://127.0.0.1:9030/logout' [GET] of elog>}<br><br>File \"/usr/local/lib/python3.8/site-packages/werkzeug/routing.py\", line 2049, in match<br>  raise NotFound()<br>variables: {'self': <werkzeug.routing.MapAdapter object at 0x7ff27922f610>, 'path_info': '/logout', 'method': 'GET', 'return_rule': True, 'query_args': {}, 'websocket': False, 'require_redirect': False, 'domain_part': '', 'path_part': '/logout', 'path': '|/logout', 'have_match_for': set(), 'websocket_mismatch': False, 'rule': <Rule '/static/<filename>' (OPTIONS, GET, HEAD) -> static>, 'rv': None}<br><br>",
      errortype: "<class 'werkzeug.exceptions.NotFound'>",
      httpmethod: "GET",
      id: "15817298993158030234",
      ip: "172.21.0.1",
      postvalues: "{}",
      referrer: "None",
      requestargs: "{}",
      requestpath: "/logout",
      useragent:
        "Mozilla/5.0 (X11; Linux x86_64; rv:100.0) Gecko/20100101 Firefox/100.0",
      userbrowser: "Firefox",
      userbrowserversion: "major.minor.patch",
      userplatform: "Linux",
      when: "2022-04-20T08:46:53.004188Z",
    },
  ],
  draw: 14,
  recordsFiltered: 8,
  recordsTotal: 13,
};
